# Python base image
FROM python:3.9-slim
# create and set the working directory
WORKDIR /app
# copy the current directory contents into the container at /app
COPY . /app
# install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Ensure asset directory exists and is accessible
RUN mkdir -p /app/asset
# Mark /app/asset as a volume to persist data
VOLUME ["/app/asset"]
# expose the port the app runs on
EXPOSE 8002
# run the FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]

# docker build -t 2_evaluation:latest .
# docker run -d --name 2_evaluation -p 8002:8002 2_evaluation
# docker images
# docker ps
# docker stop / start / rm / logs
# http://localhost:8002/docs#/ 
# docker rmi -f / docker system df / docker builder prune -f

# docker login
# docker tag 2_evaluation:latest jiaqiqi/2_evaluation:latest
# docker push jiaqiqi/2_evaluation:latest
