# Python base image
FROM python:3.9-slim
# create and set the working directory
WORKDIR /app
# copy the current directory contents into the container at /app
COPY . /app
# install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# expose the port the app runs on
EXPOSE 8003
# run the FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"]

# docker build -t 3_assurance:latest .
# docker run -d --name 3_assurance -p 8003:8003 3_assurance
# docker images
# docker ps
# docker stop / start / rm / logs
# http://localhost:8003/docs#/ 
# docker rmi -f / docker system df / docker builder prune -f

# docker login
# docker tag 3_assurance:latest jiaqiqi/3_assurance:latest
# docker push jiaqiqi/3_assurance:latest
