# Python base image
FROM python:3.9-slim
# create and set the working directory
WORKDIR /app
# copy the current directory contents into the container at /app
COPY . /app
# install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# expose the port the app runs on
EXPOSE 8004
# run the FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8004"]

# docker build -t 4_verification:latest .
# docker run -d --name 4_verification -p 8004:8004 4_verification
# docker images
# docker ps
# docker stop / start / rm / logs
# http://localhost:8004/docs#/ 
# docker rmi -f / docker system df / docker builder prune -f

# docker login
# docker tag 4_verification:latest jiaqiqi/4_verification:latest
# docker push jiaqiqi/4_verification:latest
